// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmEqpsh9vZINE2XUDbmctftFdfHJdiOgI',
    appId: '1:945965909253:web:9e7997d9f90b1e9eeee36c',
    messagingSenderId: '945965909253',
    projectId: 'flutterauthapp-24f51',
    authDomain: 'flutterauthapp-24f51.firebaseapp.com',
    storageBucket: 'flutterauthapp-24f51.firebasestorage.app',
    measurementId: 'G-21R1F05PJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_B849uZqZkLsBmKH_1KkFhiCjZeuMiAg',
    appId: '1:945965909253:android:79cca8164b2b2784eee36c',
    messagingSenderId: '945965909253',
    projectId: 'flutterauthapp-24f51',
    storageBucket: 'flutterauthapp-24f51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmHaFgAIWG1X9H3Llo7O4qwehN69AsCU',
    appId: '1:945965909253:ios:a56ece43dbcb9f2deee36c',
    messagingSenderId: '945965909253',
    projectId: 'flutterauthapp-24f51',
    storageBucket: 'flutterauthapp-24f51.firebasestorage.app',
    iosBundleId: 'com.example.firstTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmHaFgAIWG1X9H3Llo7O4qwehN69AsCU',
    appId: '1:945965909253:ios:a56ece43dbcb9f2deee36c',
    messagingSenderId: '945965909253',
    projectId: 'flutterauthapp-24f51',
    storageBucket: 'flutterauthapp-24f51.firebasestorage.app',
    iosBundleId: 'com.example.firstTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmEqpsh9vZINE2XUDbmctftFdfHJdiOgI',
    appId: '1:945965909253:web:5db88a5fa73eef03eee36c',
    messagingSenderId: '945965909253',
    projectId: 'flutterauthapp-24f51',
    authDomain: 'flutterauthapp-24f51.firebaseapp.com',
    storageBucket: 'flutterauthapp-24f51.firebasestorage.app',
    measurementId: 'G-GNK4CHNNWL',
  );
}
